server:
  port: 9000
zuul:
  routes:
    pro:
      path: /pro/**
      url: http://gw.api.winxuan.com/router/rest
    dev:
      path: /dev/**
      url: http://sandbox.api.winxuan.com/router/rest

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
